server:
  port: 8096
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: manual
    consumer:
      group-id: payment-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
idempotency:
  ttl: 24h
resilience4j:
  circuitbreaker:
    instances:
      paymentController:
        register-health-indicator: true
        sliding-window-size: 15
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 5s
        permitted-number-of-calls-in-half-open-state: 4
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
rate:
  limiter:
    buckets:
      capacity: 150
    refill:
      tokens: 10
      period: 5s
integration:
  kafka:
    topics:
      saga:
        order-creation-status: order.creation.status.event
      payment:
        create: payment.create.command
        refund: payment.refund.command